import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/theme.dart';
import 'core/supabase_client.dart';
import 'data/vault_repository.dart';
import 'features/auth/auth_page.dart';
import 'features/dashboard/dashboard_page.dart';
import 'features/search/search_page.dart';
import 'features/settings/settings_page.dart';
import 'features/capture/capture_sheet.dart';
import 'models/vault_item.dart';

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); await initializeSupabase(); runApp(const ProviderScope(child: VaultApp())); }
class VaultApp extends StatelessWidget { const VaultApp({super.key}); @override Widget build(BuildContext context) => MaterialApp(title:'Vault',debugShowCheckedModeBanner:false,theme:vaultTheme(),home:const _AuthGate()); }
class _AuthGate extends StatelessWidget { const _AuthGate(); @override Widget build(BuildContext context) { if (!supabaseConfigured) return const VaultShell(); return StreamBuilder<AuthState>(stream:supabase.auth.onAuthStateChange,builder:(context,_) => supabase.auth.currentSession == null ? const AuthPage() : const VaultShell()); } }
class VaultShell extends ConsumerStatefulWidget { const VaultShell({super.key}); @override ConsumerState<VaultShell> createState()=>_VaultShellState(); }
class _VaultShellState extends ConsumerState<VaultShell> {
  int index=0;
  final pages=<String>['Dashboard','Inbox','Notes / Thoughts','AI Conversations','Saved Content','Tools','Collections','Search','Settings'];
  @override void initState(){super.initState(); Future.microtask(()=>ref.read(vaultRepositoryProvider).load());}
  @override Widget build(BuildContext context){ final content=switch(index){0=>DashboardPage(onCapture:(t)=>showCaptureSheet(context,ref.read(vaultRepositoryProvider),initial:t)),7=>const SearchPage(),8=>const SettingsPage(),_=>_PlaceholderPage(title:pages[index],index:index)}; return Scaffold(body:LayoutBuilder(builder:(context,box){final mobile=box.maxWidth<800;return Row(children:[if(!mobile)_Sidebar(index:index,onSelect:(i)=>setState(()=>index=i),onCapture:()=>showCaptureSheet(context,ref.read(vaultRepositoryProvider))),Expanded(child:content)]);}),floatingActionButton:MediaQuery.sizeOf(context).width<800?FloatingActionButton(onPressed:()=>showCaptureSheet(context,ref.read(vaultRepositoryProvider)),backgroundColor:VaultColors.red,child:const Icon(Icons.add_rounded)):null); }
}
class _Sidebar extends StatelessWidget { final int index; final ValueChanged<int> onSelect; final VoidCallback onCapture; const _Sidebar({required this.index,required this.onSelect,required this.onCapture}); @override Widget build(BuildContext context){const items=[(Icons.grid_view_rounded,'Dashboard'),(Icons.inbox_outlined,'Inbox'),(Icons.bolt_outlined,'Notes / Thoughts'),(Icons.forum_outlined,'AI Conversations'),(Icons.bookmark_border_rounded,'Saved Content'),(Icons.build_outlined,'Tools'),(Icons.folder_open_outlined,'Collections'),(Icons.search_rounded,'Search')];return Container(width:246,decoration:const BoxDecoration(color:VaultColors.surface,border:Border(right:BorderSide(color:VaultColors.border))),child:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(14,18,14,14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:31,height:31,decoration:BoxDecoration(color:VaultColors.red,borderRadius:BorderRadius.circular(9)),child:const Icon(Icons.all_inclusive_rounded,color:Colors.white,size:17)),const SizedBox(width:9),const Text('VAULT',style:TextStyle(fontFamily:'Geist Mono',fontWeight:FontWeight.w700,letterSpacing:1.5,fontSize:13))]),const SizedBox(height:24),Padding(padding:const EdgeInsets.symmetric(horizontal:6),child:SizedBox(width:double.infinity,height:40,child:OutlinedButton.icon(onPressed:onCapture,icon:const Icon(Icons.add_rounded,size:17),label:const Text('Quick capture')))),const SizedBox(height:18),...items.asMap().entries.map((e)=>_NavItem(icon:e.value.$1,label:e.value.$2,active:index==e.key,onTap:()=>onSelect(e.key))),const Spacer(),_NavItem(icon:Icons.settings_outlined,label:'Settings',active:index==8,onTap:()=>onSelect(8)),const SizedBox(height:4),const Padding(padding:EdgeInsets.all(8),child:Text('⌘ K  Search    ⌘ N  Capture',style:TextStyle(fontFamily:'Geist Mono',fontSize:9,color:VaultColors.muted)))])));}}
class _NavItem extends StatelessWidget { final IconData icon; final String label; final bool active; final VoidCallback onTap; const _NavItem({required this.icon,required this.label,required this.active,required this.onTap}); @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:2),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(9),child:AnimatedContainer(duration:const Duration(milliseconds:160),padding:const EdgeInsets.symmetric(horizontal:10,vertical:9),decoration:BoxDecoration(color:active?VaultColors.redSoft:Colors.transparent,borderRadius:BorderRadius.circular(9)),child:Row(children:[Icon(icon,size:17,color:active?VaultColors.red:VaultColors.muted),const SizedBox(width:10),Text(label,style:TextStyle(fontSize:12,color:active?VaultColors.text:VaultColors.muted,fontWeight:active?FontWeight.w600:FontWeight.w400))]))));}
class _PlaceholderPage extends StatelessWidget { final String title; final int index; const _PlaceholderPage({required this.title,required this.index}); @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('This surface is wired into the Vault navigation and ready for its CRUD view.',style:TextStyle(color:VaultColors.muted)),const SizedBox(height:24),Expanded(child:Center(child:Container(padding:const EdgeInsets.all(26),decoration:BoxDecoration(color:VaultColors.surface,border:Border.all(color:VaultColors.border),borderRadius:BorderRadius.circular(16)),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(index==6?Icons.folder_open_rounded:Icons.auto_awesome_outlined,size:28,color:VaultColors.red),const SizedBox(height:12),const Text('Demo workspace',style:TextStyle(fontWeight:FontWeight.w600)),const SizedBox(height:5),const Text('Connect Supabase to make this surface persistent.',style:TextStyle(color:VaultColors.muted,fontSize:12))]))))]));}
}
